version: "3.8"

volumes:
  postgis_data:
  pgadmin_data:

services:
  server:
    container_name: tsod-gis-server
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgis
    command: ./wait-for.sh ${POSTGIS_HOST}:${POSTGIS_PORT} -- java -jar spring-postgis.jar

  postgis:
    container_name: ${POSTGIS_HOST}
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testDB
    ports:
      - ${POSTGIS_PORT}:${POSTGIS_PORT}
    volumes:
      - "postgis_data:/var/lib/postgresql/data"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 50
    ports:
      - "16543:80"
    depends_on:
      - postgis
