spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  data:
    rest:
      base-path: api/test/v1
