spring:
  datasource:
    url: jdbc:postgresql://${POSTGIS_HOST:localhost}:${POSTGIS_PORT:5432}/${POSTGIS_DB:testDB}
    username: ${POSTGIS_USER:postgres}
    password: ${POSTGIS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  data:
    rest:
      base-path: api/test/v1
